# Generated by Django 5.2.1 on 2025-05-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidencias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(upload_to='cobros/')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidencias.evidencia')),
            ],
        ),
    ]
