# Generated by Django 5.2.1 on 2025-05-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_initial'),
        ('reclamos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidencias.evidencia'),
        ),
    ]
