# Generated by Django 5.2.1 on 2025-05-24 02:53

import evidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(upload_to=evidencias.models.evidencia_upload_path),
        ),
    ]
